name: CS_9 YAML

on:
  push:
    branches:
      - main
      
jobs:
  open-git-on-a-virtual-machine:
    runs-on: windows-latest
    steps:
      - name: Copy to host directory
        uses: actions/checkout@v2
      - name: Copy files to destination directory
        run: |
          powershell.exe -Command "Copy-Item -Path G:\\adir.hull.ac.uk\home\662\662233\Desktop\actions-runner* -Destination C:\inetpub\wwwroot -force"
        
