name: CS_9 YAML

on:
  push:
    branches:
      - main

jobs:
  open-git-on-a-virtual-machine:
    runs-on: windows-latest
    steps:
      - name: Copy to host directory
        uses: actions/checkout@v2
      - name: Copy files to destination directory
      - name: Copy files to destination directory
        run: |
          powershell.exe -Command "Copy-Item -Path C:\Users\jason\actions-runner\_work\Student-Digital-Service* -Destination C:\inetpub\wwwroot -force"
