name: CS_9 YAML

on:
  push:
    branches:
      - main
      
jobs:
  open-git-on-a-virtual-machine:
    runs-on: windows-latest
    steps:
      - name: Copy to host directory
        uses: actions/checkout@v2
